title: Lian Liu's Homepage
page-top-title: Lian Liu
top-section-bg-text: Computer Architecture
home-subtitle: Lian Liu's homepage
copyright-text: '&copy; Lian Liu 2023-2024. All Rights Reserved.'

home-subtitle: "Welcome to My Academic Webpage"
publications-subtitle: "My Publications"
awards-subtitle: "My Awards"

home-md: "home.md"
publications-md: "publications.md"
awards-md: "awards.md"
